### ISSUE TITLE
NumberTextValue is not binding properly

### ISSUE THREAD

**Issue by Abubakkar-M** [surajmathe/intl-input-phone#1]
After getting the API response, i'm trying to update the NumberTextValue value but it's not updating.

**Comment by surajmathe** [comment]
what value you are trying to set?
As per code sample the value you are trying to set should be below format:
"{countrycode} {value}"
e.g. - "+1 3235634245"

**Comment by Abubakkar-M** [comment]
yes, the same format (+971 2376482342)

**Comment by Abubakkar-M** [comment]
yeah it's working fine. Thanks.
