### ISSUE TITLE
Reactive forms support

### ISSUE THREAD

**Issue by eso32** [surajmathe/intl-input-phone#2]
Hey!

Nice work! Are you planning to support Angular's reactive forms in the nearest future?

**Comment by surajmathe** [comment]
I am marking this issue as an enhancement and will start working on it as soon as possible.

**Comment by thucngdg** [comment]
Can you process it plz, i ultra need it, i can't handle initvalues. Should i set NumberModel + outputValue.Number (NumberResult) for initValue?

**Comment by surajmathe** [comment]
@thucngdg plz look into the answer on this https://github.com/surajmathe/intl-input-phone/issues/1#issuecomment-486513829
and if it does not work then let me know what value you are trying to set?

**Comment by surajmathe** [comment]
Hi @eso32, @thucngdg ,
Plz look into the updated version of the plugin.
[Click Here](https://intl-input-phone-demo.stackblitz.io/#CustomizationReactiveForm) to get updated version.
