### ISSUE TITLE
How can we reset the phone number

### ISSUE THREAD

**Issue by waynehong789** [surajmathe/intl-input-phone#3]
The code looks like that:

in html: 

form [formGroup]="sampleForm"
  <intl-input-phone
        name="phone"
        formControlName="phone"
        [NumberTextValue]="NumberModel"
        [ConfigurationOption]="configOption2"
        (OnNumberChange)="onNumberChage($event)"
      ></intl-input-phone>
form

in TS:
onNumberChage(outputResult: NumberResult) {
    if (outputResult.Number) {
      this.sampleForm.reset();
    }
  }

After the sampleForm reset, the number still existing in the input field.

And I tried to set [NumberTextValue] = '', but it doesn't work.

Could you please let me know how to reset the value of input number? Thanks

**Comment by surajmathe** [comment]
Hi @waynehong789,
You can reset the value by using form control, Please find the sample code below for the same.

    let numberReset : NumberResult = new NumberResult();
    numberReset.Number = "";
    numberReset.CountryModel = 
    {
      CountryPhoneCode : '',
      CustomFlagUrl :'',
      FlagCssClass : '',
      ISOCode : 'IN',
      InputMasking:'',
      IsShowCustomFlag:false,
      Name:''
    };
    this.sampleForm.controls['sampleReactiveControl'].setValue(numberReset);

Please let me know if it works :)

**Comment by waynehong789** [comment]
Hi @surajmathe,

Thanks for your reply. 
It looks should work, but I have not test it.
BTW, I am using another lib called "ngx-intl-tel-input".

Best Regards

Wayne
