### ISSUE TITLE
changing the flag

### ISSUE THREAD

**Issue by ronyeh3** [surajmathe/intl-input-phone#4]
when changing the flag, **after setting the number**, the new area code **value** doesn't updates to the new one.

**Comment by surajmathe** [comment]
Hi @ronyeh3 ,
Can you provide brief information about the scenario?
Because when you change any flag from the dropdown then according to that country masking will also be changed and after completing the input field you will get the updated value.

**Comment by ronyeh3** [comment]
a stupid user may complete the input field **and only then** change the flag, thus the value will be a wrong one.
i made a workaround to overcome such issue. im retrieving the input element from the dom and concatenating the country code by myself.
 im just letting you know about this. 
many thanks for your work
