### ISSUE TITLE
ERROR TypeError: $(...).select2 is not a function

### ISSUE THREAD

**Issue by Jaysojitra13** [surajmathe/intl-input-phone#6]
I followed your steps to create the basic selector. But facing this issue 
`ERROR TypeError: $(...).select2 is not a function `

**Comment by surajmathe** [comment]
Hi @Jaysojitra13 ,
Are you sure you include the below script in index.html file?


<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.3.4/jquery.inputmask.bundle.min.js"></script>
